FROM pytorch/pytorch
RUN apt-get update && apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    tzdata \
    libopencv-dev \
    libgl1-mesa-dev
RUN pip install -U pip
RUN pip install jupyter scipy matplotlib opencv-python sklearn pandas jupyterlab
CMD ["jupyter", "lab", "--allow-root", "--port", "8888", "--ip", "0.0.0.0"]