FROM pytorch/pytorch:1.5.1-cuda10.1-cudnn7-runtime
RUN apt-get update && apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
RUN pip install -U pip
RUN mkdir -p /root/src
COPY requirements.txt /root/src/
WORKDIR /root/src
RUN pip install -r requirements.txt
RUN git clone https://github.com/NVIDIA/apex
RUN cd apex && pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
RUN pip install jupyter jupyterlab
CMD ["jupyter", "lab", "--allow-root", "--port", "8888", "--ip", "0.0.0.0"]